config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'user/omniauth_callbacks' }
  get '@:username', to: 'user/info#show', as: 'user'
  namespace :user do
    get 'recommend', to: 'recommend#show'
    get 'edit', to: 'info#edit'
    patch 'update', to: 'info#update'
    delete 'delete', to: 'info#delete'
  end

  namespace :api do
    get 'gifscom/fetch_meta'
  end

  resources :gifs
  scope 'tags' do
    get '/', to: 'tags#index', as: :tags
    get ':tag_name', to: 'tags#show', as: :tag
  end
end

app/models/gif.rb
# frozen_string_literal: true

class Gif < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  acts_as_taggable

  include RemoteImage
  include TagList

  validates :title, presence: true
  validates :source_url,
    format: /\A#{URI::DEFAULT_PARSER.make_regexp(%w[http https])}\z/
  validates :image,
    attached: true,
    content_type: 'image/gif',
    size: { less_than: Settings.gifs.upload.max_size },
    dimension: {
      width: { max: Settings.gifs.upload.max_width },
      height: { max: Settings.gifs.upload.max_height },
    }
  validate :custom_validator

  default_scope -> { order(created_at: :desc) }

  def editable?(check_user)
    user == check_user
  end

  private

  def custom_validator
    errors.add(:base, 'Must be boolean') if public.nil?
  end
end

app/controllers/gifs_controller.rb
# frozen_string_literal: true

class GifsController < ApplicationController
  include GifsHelper
  include PagesHelper

  before_action :authenticate_user!, except: %i[index show]
  before_action :set_gif, only: %i[show edit update destroy]
  before_action :can_edit?, only: %i[edit update destroy]

  # GET /gifs
  # GET /gifs.json
  def index
    @gifs = Gif.all.with_attached_image
  end

  # GET /gifs/1
  # GET /gifs/1.json
  def show
    respond_to do |format|
      format.html { render :show }
      format.gif { redirect_to image_public_url(@gif.image) }
      format.thumb_gif { redirect_to thumbnail_image(@gif.image) }
    end
  end

  # GET /gifs/new
  def new
    @gif = Gif.new
  end

  # GET /gifs/1/edit
  def edit; end

  # POST /gifs
  # POST /gifs.json
  def create
    @gif = Gif.new(gif_params)

    respond_to do |format|
      if @gif.save
        format.html { redirect_to @gif, notice: t('.success') }
        format.json { render :show, status: :created, location: @gif }
      else
        format.html { render :new }
        format.json { render json: @gif.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifs/1
  # PATCH/PUT /gifs/1.json
  def update
    respond_to do |format|
      if @gif.update(gif_params)
        format.html { redirect_to @gif, notice: t('.success') }
        format.json { render :show, status: :ok, location: @gif }
      else
        format.html { render :edit }
        format.json { render json: @gif.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifs/1
  # DELETE /gifs/1.json
  def destroy
    @gif.destroy
    respond_to do |format|
      format.html { redirect_to gifs_url, notice: t('.success') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_gif
    @gif = Gif.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def gif_params
    params
      .require(:gif)
      .permit(:image, :remote_image_url, :title, :source_url, :tag_list)
      .merge(user: current_user)
  end

  def can_edit?
    raise Forbidden unless @gif.editable?(current_user)
  end
end

app/helpers/gifs_helper.rb
# frozen_string_literal: true

module GifsHelper
  def image_public_url(resource)
    if Rails.env.production?
      url = URI.parse(resource.service_url)
      url.query = ''
      url.to_s.delete_suffix('?')
    else
      full_url_for(resource)
    end
  end
end

app/views/gifs/_form.html.erb
<%= javascript_pack_tag 'gif_form', defer: true %>

<%= form_with(model: gif, local: true) do |form| %>
  <% if gif.errors.any? %>
    <div id="error_explanation">
      <h2><%= I18n.t('errors.template.body') %>:</h2>
    </div>
  <% end %>

  <div class="columns">
    <div class="column is-two-fifths">
      <div class="field">
        <div class="file">
          <%= form.label :image, class: 'file-label' do %>
            <%= form.file_field :image, class: 'file-input', accept: 'image/gif' %>
            <span class="file-cta">
              <span class="file-icon">
                <i class="fas fa-upload"></i>
              </span>
              <span class="file-label">
                アップロードするGIFを選択
              </span>
            </span>
          <% end %>
        </div>
        <div>
          <p>or...</p>
          <%= form.label :remote_image_url, class: 'label' %>
          <%= form.text_field :remote_image_url, class: 'input', placeholder: '例) https://j.gifs.com/OMz2yQ.gif' %>
          <p class="help">現在、gifs.comのDirect Linkからのみ取り込めます。自動でタイトル、切り抜き元URLも取り込みます！</p>
        </div>
        <%= error_message(gif, :image) %>
        <figure class="image">
          <%= image_tag gif.image.attached? ? gif.image : '', id: 'gif-preview' %>
        </figure>
      </div>
    </div>

    <div class="column">
      <div class="field">
        <%= form.label :title, class: 'label' %>
        <%= form.text_field :title, class: 'input', placeholder: '簡潔で分かりやすいタイトル' %>
        <%= error_message(gif, :title) %>
      </div>

      <div class="field">
        <%= form.label :source_url, class: 'label' %>
        <%= form.url_field :source_url, class: 'input', placeholder: '例) https://youtu.be/ao4QU9HTAt8?t=6113' %>
        <p class="help">httpまたはhttpsから入力する必要があります。</p>
        <%= error_message(gif, :source_url) %>
      </div>

      <div class="field">
        <%= form.label :tag_list, class: 'label' %>
        <%= form.text_field :tag_list, class: 'tagify', value: gif.tag_list.map { |tag| {value: tag} }.to_json %>
        <p class="help">YouTuber名、所属グループ名、かわいい、など書くと後から見つけやすくなります。Enterでタグを1つ確定します。</p>
      </div>

      <p><%= link_to '利用規約', page_path('terms_of_service'), target: 'noopenner' %>に同意して推せ↓</p>

      <div class="actions">
        <%= form.button type: 'button', id: 'submit_button', class: 'button is-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/gifs/_gifgrid.html.erb
<div class="tile is-ancestor gifgrid">
  <div class="tile is-parent">
    <% if gifs.empty? %>
      <div class="notification">
        <p>なんもないで</p>
      </div>
    <% else %>
      <% gifs.each do |gif| %>
        <%= link_to gif, class: 'tile is-3' do %>
          <figure class="image">
            <%= image_tag '', class: 'gif lazyload', 'data-src': url_for(thumbnail_image(gif.image)), alt: gif.title %>
          </figure>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/gifs/edit.html.erb
<h1><%= title 'Editing Gif' %></h1>

<%= render 'form', gif: @gif %>

<%= link_to 'Show', @gif %> |
<%= link_to 'Back', gifs_path %>

app/views/gifs/index.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title"><%= title 'GIFs' %></h1>
      <h2 class="subtitle">今日も推しが尊い</h2>
    </div>
  </div>
</section>

<p>推せ→ <%= link_to 'Upload GIF', new_gif_path, class: 'button is-primary' %></p>

<hr />

<p>アップロードされたGIFたち</p>

<%= render partial: 'gifs/gifgrid', locals: { gifs: @gifs } %>

app/views/gifs/new.html.erb
<h1><%= title 'New Gif' %></h1>

<%= render 'form', gif: @gif %>

<%= link_to 'Back', gifs_path %>

app/views/gifs/show.html.erb
<%= javascript_pack_tag 'share', defer: true %>

<% description "vGIFにアップロードされたGIF、「#{@gif.title}」のページ - #{default_meta_tags[:description]}" %>
<% keywords @gif.tag_list.join(',') %>
<% set_meta_tags og: { image: image_public_url(ogp_image(@gif.image)) } %>
<% set_meta_tags twitter: { card: 'summary_large_image' } %>

<%= image_tag @gif.image, alt: @gif.title %>

<div class="content">
  <p class="title is-3 is-inline"><%= title @gif.title %></p>

  <% if @gif.editable?(current_user) %>
    <div class="buttons is-inline">
      <%= link_to edit_gif_path(@gif), class: 'button is-link is-outlined' do %>
        <span class="icon">
          <i class="fas fa-edit"></i>
        </span>
      <% end %>
      <button id="delete-button" class="button is-danger is-outlined open-modal">
        <span class="icon">
          <i class="far fa-trash-alt"></i>
        </span>
      </button>

      <div class="modal">
        <div class="modal-background"></div>
        <div class="modal-content">
          <div class="box">
            <p>GIFの削除を行います。</p>
            <p><strong>この操作は取り消せません。</strong></p>
            <%= link_to '本当に削除する', gif_path(@gif), method: :delete, class: 'button is-danger' %>
          </div>
        </div>
        <button class="modal-close is-large" aria-label="close"></button>
      </div>

    </div>
  <% end %>

  <p>
    <% @gif.tag_list.map do |tag| %>
      <%= link_to tag_path(tag) do %>
        <span class="tag is-link">#<%= tag %></span>
      <% end %>
    <% end %>
  </p>
</div>

<div class="field has-addons copy-button">
  <div class="control has-icons-right">
    <%= url_field_tag 'public_url', gif_url(@gif, format: :gif), class: 'input', readonly: true %>
    <%= hidden_field_tag 'direct_url', image_public_url(@gif.image) %>
  </div>
  <div class="control">
    <button class="button is-info has-tooltip-arrow" data-tooltip-tmp="Copied!">
      <span class="icon">
        <i class="fas fa-copy"></i>
      </span>
    </button>
  </div>
</div>

<div class="field">
  <button id="share-button" class="button is-primary is-small">
    <span class="icon">
      <i class="fas fa-share-alt-square"></i>
    </span>
    <span>Share</span>
  </button>
</div>

<div class="content">
  <p>
    <b><%= Gif.human_attribute_name(:source_url) %></b>
    <%= link_to @gif.source_url, @gif.source_url, target: '_blank', rel: 'ugc noopener noreferrer' %>
  </p>

  <p>
    <b><%= Gif.human_attribute_name(:user) %></b>
    <%= link_to @gif.user.displayname, @gif.user %>
  </p>
</div>