config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'user/omniauth_callbacks' }
  get '@:username', to: 'user/info#show', as: 'user'
  namespace :user do
    get 'recommend', to: 'recommend#show'
    get 'edit', to: 'info#edit'
    patch 'update', to: 'info#update'
    delete 'delete', to: 'info#delete'
  end

  namespace :api do
    get 'gifscom/fetch_meta'
  end

  resources :gifs
  scope 'tags' do
    get '/', to: 'tags#index', as: :tags
    get ':tag_name', to: 'tags#show', as: :tag
  end
end

app/views/layouts/_gtag.html.erb
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-162855092-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  document.addEventListener('turbolinks:load', e => {
    gtag('config', 'UA-162855092-1', {
      'page_title': e.target.title,
      'page_path': e.data.url.replace(window.location.protocol + '//' + window.location.hostname + (window.location.port && ':' + window.location.port), ''),
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'favicon.gif', type: 'image/gif' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= display_meta_tags default_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', async: true %>
    <%= javascript_pack_tag 'layout', 'data-turbolinks-track': 'reload' %>
    <script defer src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" data-mutate-approach="sync"></script>
    <script defer src="https://gistcdn.githack.com/i544c/ac5b0e0d76546e8f5c86f8e566eee7dd/raw/hire_me.js"></script>
    <%= render 'layouts/gtag' if Rails.env.production? %>
  </head>

  <body>
    <nav class="navbar is-link" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to 'vGIF', root_path, class: 'navbar-item' %>
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarMenu">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarMenu" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to 'GIFs', gifs_path, class: 'navbar-item' %>
          <%= link_to 'Tags', tags_path, class: 'navbar-item' %>
          <%= link_to 'Recommend', user_recommend_path, class: 'navbar-item' %>
        </div>
        <div class="navbar-end">
          <% if user_signed_in? %>
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link"><%= current_user.displayname.truncate(10) %></a>
              <div class="navbar-dropdown is-right">
                <%= link_to 'ユーザページ', current_user, class: 'navbar-item' %>
                <%= link_to 'ユーザ設定', user_edit_path, class: 'navbar-item' %>
                <hr class="dropdown-divider" />
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'navbar-item has-text-danger' %>
              </div>
            </div>
          <% else %>
            <%= link_to 'Twitterアカウントでログイン', :user_twitter_omniauth_authorize, class: 'navbar-item' %>
            <%= link_to 'developerでログイン', :user_developer_omniauth_authorize, class: 'navbar-item' unless Rails.env.production? %>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="<%= @no_container ? '' : 'my-container' %> flex-1">
      <% if notice %>
        <div class="notification is-primary is-light">
          <button class="delete"></button>
          <%= notice %>
        </div>
      <% end %>

      <% if alert %>
        <div class="notification is-warning">
          <button class="delete"></button>
          <%= alert %>
        </div>
      <% end %>

      <%= yield %>
    </div>

    <footer class="footer">
      <div class="content has-text-centered">
        <p>
          <%= link_to '利用規約', page_path('terms_of_service') %>
          、
          <%= link_to 'プライバシーポリシー', page_path('privacy_policy') %>
          見てね。
        </p>
        <p>
          <a href="https://twitter.com/_leo_isaac" target="noopener">金欠でヲタクな学生</a>
          が
          <a href="https://github.com/i544c/vgif" target="noopenner">個人で作っています</a>
          。
        </p>
      </div>
    </footer>
  </body>
</html>