config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'user/omniauth_callbacks' }
  get '@:username', to: 'user/info#show', as: 'user'
  namespace :user do
    get 'recommend', to: 'recommend#show'
    get 'edit', to: 'info#edit'
    patch 'update', to: 'info#update'
    delete 'delete', to: 'info#delete'
  end

  namespace :api do
    get 'gifscom/fetch_meta'
  end

  resources :gifs
  scope 'tags' do
    get '/', to: 'tags#index', as: :tags
    get ':tag_name', to: 'tags#show', as: :tag
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
    :omniauthable, omniauth_providers: %i[twitter developer]

  has_many :gifs, dependent: :destroy
  acts_as_taggable

  include TagList

  validates :username, presence: true, uniqueness: true
  validates :displayname, presence: true, length: { in: 1..30 }

  # rubocop:disable Metrics/AbcSize
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = "#{auth.provider}-#{auth.uid}@example.com"
      user.password = Devise.friendly_token[0, 20]
      user.username = auth.info.nickname || auth.info.name
      user.displayname = auth.info.name
    end
  end
  # rubocop:enable Metrics/AbcSize

  def to_param
    username
  end
end

app/controllers/user/info_controller.rb
# frozen_string_literal: true

class User::InfoController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :set_user, except: :show

  def show
    @user = User.find_by!(username: params[:username])
  end

  def edit; end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: t('.success') }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @user.destroy

    flash[:notice] = t('.success')
    redirect_to root_path
  end

  private

  def set_user
    # current_userのままやると、form以外に影響を及ぼす為
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:displayname, :tag_list)
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  protect_from_forgery except: :developer

  def twitter
    authorize
  end

  def developer
    authorize
  end

  private

  # rubocop:disable all
  def authorize
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      if is_navigational_format?
        set_flash_message(:notice, :success, kind: 'Twitter')
      end
    else
      session['devise.twitter_data'] = request.env['omniauth.auth'].except('extra')
      redirect_to new_user_session_url
    end
  end
  # rubocop:enable all
end

app/controllers/user/recommend_controller.rb
# frozen_string_literal: true

class User::RecommendController < ApplicationController
  before_action :authenticate_user!

  def show
    @tags = current_user.tag_list
    @gifs = Gif.tagged_with(@tags, any: true).with_attached_image
  end
end

app/controllers/users/info_controller.rb
class Users::InfoController < ApplicationController
  def show
    @user = User.find_by(username: params[:username])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  protect_from_forgery except: :developer

  def twitter
    authorize
  end

  def developer
    authorize
  end

  def failure
    set_flash_message! :alert, :failure, kind: 'Twitter', reason: failure_message
    redirect_to root_path
  end

  private

  def authorize
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Twitter') if is_navigational_format?
    else
      session['devise.twitter_data'] = request.env['omniauth.auth'].except('extra')
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/user/info_helper.rb
# frozen_string_literal: true

module User::InfoHelper
end

app/helpers/user/recommend_helper.rb
# frozen_string_literal: true

module User::RecommendHelper
end

app/views/user/info/edit.html.erb
<p class="title is-3">ユーザ設定</p>

<%= form_with(model: @user, url: user_update_path) do |form| %>
  <div class="field">
    <%= form.label :displayname, class: 'label' %>
    <%= form.text_field :displayname, class: 'input' %>
    <%= error_message(@user, :displayname) %>
  </div>

  <div class="field">
    <%= form.label :tag_list, class: 'label' %>
    <%= form.text_field :tag_list, class: 'tagify', value: current_user.tag_list.map { |tag| {value: tag} }.to_json %>
    <p class="help">YouTuber名を書くと良いでしょう。Enterでタグを1つ確定します。</p>
  </div>

  <div class="actions">
    <%= form.button type: 'button', id: 'submit_button', class: 'button is-primary' %>
  </div>
<% end %>

<hr />

<div class="message is-danger">
  <div class="message-header">
    <p>退会する場合</p>
  </div>
  <div class="message-body">
    <p>下の「退会する」をクリックすることで、あなたのアカウント情報の全てを本サービスから削除します。</p>
    <p><strong>この操作は取り消せません。</strong></p>
    <button class="button is-danger is-outlined open-modal">退会する</button>

    <div class="modal">
      <div class="modal-background"></div>
      <div class="modal-content">
        <div class="box">
          <p>ご不明・ご不満な点がありましたら、<a href="https://twitter.com/messages/compose?recipient_id=3065982787&text=vGIF%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6" target="noopener">お気軽にご連絡ください。</a></p>
          <p>また、本サービスはソースコードを公開しており、誰もが機能の追加や修正ができ、また提案することができます。こちらもご検討ください。</p>
          <p><a href="https://github.com/i544c/vgif" target="noopener">https://github.com/i544c/vgif</a></p>
          <hr />
          <p class="title is-5">それでも削除される場合...</p>
          <p>アカウント情報には、あなたがアップロードしたGIF全ても含まれ、退会を行うと直ちに削除が行われます。</p>
          <p><strong>この操作は取り消せません。</strong></p>
          <%= link_to '本当に退会する', user_delete_path, method: :delete, class: 'button is-danger' %>
        </div>
      </div>
      <button class="modal-close is-large" aria-label="close"></button>
    </div>

  </div>
</div>

app/views/user/info/show.html.erb
<% description "ユーザ「#{@user.displayname}」のページ - VTuberのGIFが集まる場所、vGIF" %>

<section class="hero">
  <div class="hero-body">
    <div class="container">
      <p class="title is-3"><%= title @user.displayname %></p>
      <p class="subtitle is-6">@<%= @user.username %></p>
    </div>
  </div>
</section>

<div class="buttons">
  <% if @user == current_user %>
    <%= link_to '編集する', user_edit_path, class: 'button is-primary' %>
  <% end %>
</div>

<div class="content">
  <p class="title is-4"><%= User.human_attribute_name('tag_list') %><p>
  <p>
    <% @user.tag_list.map do |tag| %>
      <%= link_to tag_path(tag) do %>
        <span class="tag is-link">#<%= tag %></span>
      <% end %>
    <% end %>
  </p>
</div>

<div class="content">
  <p class="title is-4">投稿したGIF</p>
  <%= render partial: 'gifs/gifgrid', locals: { gifs: @user.gifs.with_attached_image } %>
</div>